### ISSUE TITLE
Add KB4493132 for Win7 pls

### ISSUE THREAD

**Issue by hooddy** [Wohlstand/Destroy-Windows-10-Spying#1]
Please add to removable updates KB4493132 for Win7 please.

**Comment by Wohlstand** [comment]
Added just now on a quick hand!
Try it out: https://github.com/Wohlstand/Destroy-Windows-10-Spying/releases/tag/2.2.2.2.19
:fox_face: :wink: 

Please confirm that it works, then I'll close the issue.

**Comment by Wohlstand** [comment]
Okay, I'll close this :wink:
