### ISSUE TITLE
How to remove all changes DWS done to Windows?

### ISSUE THREAD

**Issue by hassaan-dev** [Wohlstand/Destroy-Windows-10-Spying#10]
Hi,

I want to reset the all changes made by DWS to my Windows 10. I did not create restore point before starting. Is there any way now to reset or remove all changes DWS done to my system?

**Comment by Wohlstand** [comment]
Original author have been noticed that It's not possible to revert some changes as some few files was been removed (except of uninstalled updates), however, I guess that you can do to revert that partially:
- clean-up file `%WinDir%\system32\drivers\etc\hosts` (remove everything you see in a list and keep the `127.0.0.1 localhost` entry only)
- in a firewall, remove all IP rules where are was installed by DWS
- some services where disabled by DWS, open classic control panel / Administrative / Services, and find some bunch of disabled services and re-enable them back
- re-enable disabled updates idk how to make that, I don't use Windows 10 (I use Linux Mint as a main OS and Windows 7 VM for windows specific tricks, and Windows 10 VM for a very rare cases of specific bugs)
- If you did remove of Metro apps, that idk how to install them back (probably through "programs & components" and in the components management)
Probably, you can try to install a Windows 10 from DVD/ISO as an update to repair some of these damages :thinking:

**Comment by hassaan-dev** [comment]
Thank you
