### ISSUE TITLE
What`s the difference between REAL and 2.* version?

### ISSUE THREAD

**Issue by necros2k7** [Wohlstand/Destroy-Windows-10-Spying#3]
subj

**Comment by Wohlstand** [comment]
**The "RE" "Renessans-Edition"**, is the remixed DWS with some updates and targeted to work on Windows 10 only. It was abused by jerks are made with using of auto-update mechanism to ship trojans. I have removed that damn, and versions produced by me now are safe.
**The 2.x DWS** is revived original Nummer's variant with few updates and fixes made by me. It's able to work on Windows 7, 8, and 8.1 also. I have revived this version as a separated branch and I releasing two different variants of DWS.
