### ISSUE TITLE
Bitdefender blocks threat

### ISSUE THREAD

**Issue by ediowar** [Wohlstand/Destroy-Windows-10-Spying#4]
![image](https://user-images.githubusercontent.com/44164186/58381601-5acb4080-7fc7-11e9-8d0c-228b61c50b79.png)
Windows 8, DWS-build-Win7881-2.2.2.2.24
[DWS.log](https://github.com/Wohlstand/Destroy-Windows-10-Spying/files/3220292/DWS.log)

**Comment by elderlabs** [comment]
Well did you read the log. The hosts file was edited. That's hardly a trojan. This executable adds a few bad hosts to the file to block them. If anything, BitDefender's being useless, as per usual, especially seeing as it's the free version. Check the file in question, and check the executable's options tab, which explains that it's going to edit that file, and a few places in the firewall. The most it's doing is adding entrys, not removing.

**Comment by ediowar** [comment]
> This executable adds a few **bad** hosts to the file to block them.

Maybe that's why Bitdefender prevents the host file changes.
[hosts_protection shield is off.txt](https://github.com/Wohlstand/Destroy-Windows-10-Spying/files/3220587/hosts_protection.shield.is.off.txt)
[hosts_protection shield is on.txt](https://github.com/Wohlstand/Destroy-Windows-10-Spying/files/3220588/hosts_protection.shield.is.on.txt)

**Comment by Wohlstand** [comment]
It's usually because the `hosts` file often used by fishing jerks are making fake sites with using of real domains, but giving, in fact, the fake replica of them which are stealing personal data of the user. The modification of that file usually happens because of viruses or trojans are making the modification.
