### ISSUE TITLE
Blocking Telemetry Breaks Windows Mail App

### ISSUE THREAD

**Issue by arthurgeron** [Wohlstand/Destroy-Windows-10-Spying#5]
After blocking telemetry Windows Mail App is not able to fetch e-mail anymore

**Comment by Wohlstand** [comment]
From which mail server?

**Comment by arthurgeron** [comment]
Outlook/Hotmail

**Comment by arthurgeron** [comment]
My work (office 365) mail also seems to not be syncing, I ran Microsoft Net Tools to monitor the traffic from  HxOutlook.exe and HxTsr.exe and the latter seems to be getting lots of "403" responses from the IP addresses it's trying to reach.

**Comment by Wohlstand** [comment]
Probably, some related domains are in etc/hosts (`C:\Windows\system32\drivers\etc\hosts`), try to edit it by notepad from Admin and remove any outlook/hotmail related domains and retry again.

**Comment by arthurgeron** [comment]
Looked like it was faling due to `deploy.static.akamaitechnologies.com`  resolving to 0.0.0.0 on hosts file

**Comment by arthurgeron** [comment]
After commenting that out mail works normally again.

**Comment by Wohlstand** [comment]
:fox_face: :+1:

**Comment by elderlabs** [comment]
It is worth noting all of the rules listed below break certain Windows 10 features. Not all of them will be noticed if you do not use/test certain Windows apps, but I have found that these are required for all features to function properly.

```
# 0.0.0.0 a-0001.a-msedge.net
# 0.0.0.0 a-0001.dc-msedge.net
# 0.0.0.0 a-0002.a-msedge.net
# 0.0.0.0 a-0003.a-msedge.net
# 0.0.0.0 a-0004.a-msedge.net
# 0.0.0.0 a-0005.a-msedge.net
# 0.0.0.0 a-0006.a-msedge.net
# 0.0.0.0 a-0007.a-msedge.net
# 0.0.0.0 a-0008.a-msedge.net
# 0.0.0.0 a-0009.a-msedge.net
# 0.0.0.0 a-0010.a-msedge.net
# 0.0.0.0 a-0011.a-msedge.net
# 0.0.0.0 a-0012.a-msedge.net
# 0.0.0.0 a-msedge.net
# 0.0.0.0 client-s.gateway.messenger.live.com
# 0.0.0.0 client.wns.windows.com
# 0.0.0.0 device.auth.xboxlive.com
# 0.0.0.0 dns.msftncsi.com
# 0.0.0.0 feedback.windows.com
# 0.0.0.0 fs.microsoft.com
# 0.0.0.0 licensing.mp.microsoft.com
# 0.0.0.0 mediaredirect.microsoft.com
# 0.0.0.0 msftncsi.com
# 0.0.0.0 officeclient.microsoft.com
# 0.0.0.0 pti.store.microsoft.com
# 0.0.0.0 settings-ssl.xboxlive.com
# 0.0.0.0 store-images.s-microsoft.com
# 0.0.0.0 storecatalogrevocation.storequality.microsoft.com
# 0.0.0.0 storeedgefd.dsx.mp.microsoft.com
# 0.0.0.0 support.microsoft.com
# 0.0.0.0 tile-service.weather.microsoft.com
# 0.0.0.0 time.windows.com
# 0.0.0.0 wdcp.microsoft.com
# 0.0.0.0 wdcpalt.microsoft.com
# 0.0.0.0 www.msftconnecttest.com
# 0.0.0.0 www.msftncsi.com
```

**Comment by Wohlstand** [comment]
@elderlabs, thanks for a list! :fox_face: 
I think I'll add the option to choose "Keep M$ online features (include Windows Store) work" or "block everything, and break work of Microsoft online services"

**Comment by Wohlstand** [comment]
And yeah, I'll auto-remove those entries when choose to support MS features to make the thing easier
